name: tutor_ed
description: TutorED

version: 1.0.0+1

environment:
  sdk: ">=2.0.0-dev.68.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  cloud_firestore: ^0.8.2
  firebase_auth: ^0.6.6
  google_sign_in: ^3.2.4
  firebase_storage: ^1.0.4
  firebase_analytics: ^1.0.4
  fluttertoast: ^2.2.5
  shared_preferences: ^0.4.3
  image_picker: ^0.4.12
  cached_network_image: ^0.5.1
  intl: ^0.15.7
  cupertino_icons: ^0.1.2
  connectivity: ^0.3.2
  font_awesome_flutter: ^8.4.0

dev_dependencies:
  flutter_test:
    sdk: flutter


flutter:
  uses-material-design: true
  assets:
    - images/
  fonts:
    - family: 'Great Vibes'
      fonts:
        - asset: fonts/GreatVibes-Regular.ttf
    - family: 'Lato'
      fonts:
        - asset: fonts/Lato-Regular.ttf